// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.28.0--rc1
// source: proto/shifu/shifu.proto

package shifu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckInstallationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInstallationRequest) Reset() {
	*x = CheckInstallationRequest{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInstallationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInstallationRequest) ProtoMessage() {}

func (x *CheckInstallationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInstallationRequest.ProtoReflect.Descriptor instead.
func (*CheckInstallationRequest) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{0}
}

type CheckInstallationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Installed     bool                   `protobuf:"varint,1,opt,name=installed,proto3" json:"installed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInstallationResponse) Reset() {
	*x = CheckInstallationResponse{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInstallationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInstallationResponse) ProtoMessage() {}

func (x *CheckInstallationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInstallationResponse.ProtoReflect.Descriptor instead.
func (*CheckInstallationResponse) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{1}
}

func (x *CheckInstallationResponse) GetInstalled() bool {
	if x != nil {
		return x.Installed
	}
	return false
}

type InstallShifuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallShifuRequest) Reset() {
	*x = InstallShifuRequest{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallShifuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallShifuRequest) ProtoMessage() {}

func (x *InstallShifuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallShifuRequest.ProtoReflect.Descriptor instead.
func (*InstallShifuRequest) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{2}
}

func (x *InstallShifuRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type InstallShifuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallShifuResponse) Reset() {
	*x = InstallShifuResponse{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallShifuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallShifuResponse) ProtoMessage() {}

func (x *InstallShifuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallShifuResponse.ProtoReflect.Descriptor instead.
func (*InstallShifuResponse) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{3}
}

func (x *InstallShifuResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InstallShifuResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetAllAvailableVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAvailableVersionsRequest) Reset() {
	*x = GetAllAvailableVersionsRequest{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAvailableVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAvailableVersionsRequest) ProtoMessage() {}

func (x *GetAllAvailableVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAvailableVersionsRequest.ProtoReflect.Descriptor instead.
func (*GetAllAvailableVersionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{4}
}

type GetAllAvailableVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []string               `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAvailableVersionsResponse) Reset() {
	*x = GetAllAvailableVersionsResponse{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAvailableVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAvailableVersionsResponse) ProtoMessage() {}

func (x *GetAllAvailableVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAvailableVersionsResponse.ProtoReflect.Descriptor instead.
func (*GetAllAvailableVersionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllAvailableVersionsResponse) GetVersions() []string {
	if x != nil {
		return x.Versions
	}
	return nil
}

type UninstallShifuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallShifuRequest) Reset() {
	*x = UninstallShifuRequest{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallShifuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallShifuRequest) ProtoMessage() {}

func (x *UninstallShifuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallShifuRequest.ProtoReflect.Descriptor instead.
func (*UninstallShifuRequest) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{6}
}

type UninstallShifuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallShifuResponse) Reset() {
	*x = UninstallShifuResponse{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallShifuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallShifuResponse) ProtoMessage() {}

func (x *UninstallShifuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallShifuResponse.ProtoReflect.Descriptor instead.
func (*UninstallShifuResponse) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{7}
}

func (x *UninstallShifuResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UninstallShifuResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{8}
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{9}
}

func (x *ListDevicesResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type GetDeviceDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceDetailsRequest) Reset() {
	*x = GetDeviceDetailsRequest{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceDetailsRequest) ProtoMessage() {}

func (x *GetDeviceDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{10}
}

func (x *GetDeviceDetailsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetDeviceDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edgedevice    *Edgedevice            `protobuf:"bytes,1,opt,name=edgedevice,proto3" json:"edgedevice,omitempty"`
	APIs          string                 `protobuf:"bytes,2,opt,name=APIs,proto3" json:"APIs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceDetailsResponse) Reset() {
	*x = GetDeviceDetailsResponse{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceDetailsResponse) ProtoMessage() {}

func (x *GetDeviceDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{11}
}

func (x *GetDeviceDetailsResponse) GetEdgedevice() *Edgedevice {
	if x != nil {
		return x.Edgedevice
	}
	return nil
}

func (x *GetDeviceDetailsResponse) GetAPIs() string {
	if x != nil {
		return x.APIs
	}
	return ""
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Age           string                 `protobuf:"bytes,5,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{12}
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Device) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Device) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Device) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

type Edgedevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Connection    string                 `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Age           string                 `protobuf:"bytes,6,opt,name=age,proto3" json:"age,omitempty"`
	Setting       string                 `protobuf:"bytes,7,opt,name=setting,proto3" json:"setting,omitempty"`
	Gateway       string                 `protobuf:"bytes,8,opt,name=gateway,proto3" json:"gateway,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edgedevice) Reset() {
	*x = Edgedevice{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edgedevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edgedevice) ProtoMessage() {}

func (x *Edgedevice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edgedevice.ProtoReflect.Descriptor instead.
func (*Edgedevice) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{13}
}

func (x *Edgedevice) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Edgedevice) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

func (x *Edgedevice) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Edgedevice) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Edgedevice) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Edgedevice) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *Edgedevice) GetSetting() string {
	if x != nil {
		return x.Setting
	}
	return ""
}

func (x *Edgedevice) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

type ForwardPortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceName    string                 `protobuf:"bytes,1,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	DevicePort    string                 `protobuf:"bytes,2,opt,name=device_port,json=devicePort,proto3" json:"device_port,omitempty"`
	LocalPort     string                 `protobuf:"bytes,3,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardPortRequest) Reset() {
	*x = ForwardPortRequest{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardPortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardPortRequest) ProtoMessage() {}

func (x *ForwardPortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardPortRequest.ProtoReflect.Descriptor instead.
func (*ForwardPortRequest) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{14}
}

func (x *ForwardPortRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *ForwardPortRequest) GetDevicePort() string {
	if x != nil {
		return x.DevicePort
	}
	return ""
}

func (x *ForwardPortRequest) GetLocalPort() string {
	if x != nil {
		return x.LocalPort
	}
	return ""
}

type ForwardPortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardPortResponse) Reset() {
	*x = ForwardPortResponse{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardPortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardPortResponse) ProtoMessage() {}

func (x *ForwardPortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardPortResponse.ProtoReflect.Descriptor instead.
func (*ForwardPortResponse) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{15}
}

func (x *ForwardPortResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RestartDeviceShifuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceName    string                 `protobuf:"bytes,1,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartDeviceShifuRequest) Reset() {
	*x = RestartDeviceShifuRequest{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartDeviceShifuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartDeviceShifuRequest) ProtoMessage() {}

func (x *RestartDeviceShifuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartDeviceShifuRequest.ProtoReflect.Descriptor instead.
func (*RestartDeviceShifuRequest) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{16}
}

func (x *RestartDeviceShifuRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{17}
}

type DeleteDeviceShifuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceName    string                 `protobuf:"bytes,1,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeviceShifuRequest) Reset() {
	*x = DeleteDeviceShifuRequest{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeviceShifuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeviceShifuRequest) ProtoMessage() {}

func (x *DeleteDeviceShifuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeviceShifuRequest.ProtoReflect.Descriptor instead.
func (*DeleteDeviceShifuRequest) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteDeviceShifuRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

type GetAllContainerNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceName    string                 `protobuf:"bytes,1,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllContainerNameRequest) Reset() {
	*x = GetAllContainerNameRequest{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllContainerNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllContainerNameRequest) ProtoMessage() {}

func (x *GetAllContainerNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllContainerNameRequest.ProtoReflect.Descriptor instead.
func (*GetAllContainerNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{19}
}

func (x *GetAllContainerNameRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

type GetAllContainerNameResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContainerNames []string               `protobuf:"bytes,1,rep,name=container_names,json=containerNames,proto3" json:"container_names,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAllContainerNameResponse) Reset() {
	*x = GetAllContainerNameResponse{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllContainerNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllContainerNameResponse) ProtoMessage() {}

func (x *GetAllContainerNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllContainerNameResponse.ProtoReflect.Descriptor instead.
func (*GetAllContainerNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{20}
}

func (x *GetAllContainerNameResponse) GetContainerNames() []string {
	if x != nil {
		return x.ContainerNames
	}
	return nil
}

type GetDeviceShifuLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceName    string                 `protobuf:"bytes,1,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	ContainerName string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceShifuLogsRequest) Reset() {
	*x = GetDeviceShifuLogsRequest{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceShifuLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceShifuLogsRequest) ProtoMessage() {}

func (x *GetDeviceShifuLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceShifuLogsRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceShifuLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{21}
}

func (x *GetDeviceShifuLogsRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *GetDeviceShifuLogsRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

type GetDeviceShifuLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           string                 `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceShifuLogsResponse) Reset() {
	*x = GetDeviceShifuLogsResponse{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceShifuLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceShifuLogsResponse) ProtoMessage() {}

func (x *GetDeviceShifuLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceShifuLogsResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceShifuLogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{22}
}

func (x *GetDeviceShifuLogsResponse) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{23}
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	IsError       bool                   `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{24}
}

func (x *CommandResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CommandResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type CompletionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partial       string                 `protobuf:"bytes,1,opt,name=partial,proto3" json:"partial,omitempty"`                         // 部分输入的命令
	CurrentDir    string                 `protobuf:"bytes,2,opt,name=current_dir,json=currentDir,proto3" json:"current_dir,omitempty"` // 当前工作目录
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionRequest) Reset() {
	*x = CompletionRequest{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionRequest) ProtoMessage() {}

func (x *CompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionRequest.ProtoReflect.Descriptor instead.
func (*CompletionRequest) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{25}
}

func (x *CompletionRequest) GetPartial() string {
	if x != nil {
		return x.Partial
	}
	return ""
}

func (x *CompletionRequest) GetCurrentDir() string {
	if x != nil {
		return x.CurrentDir
	}
	return ""
}

type CompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Completions   []string               `protobuf:"bytes,1,rep,name=completions,proto3" json:"completions,omitempty"` // 补全建议列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionResponse) Reset() {
	*x = CompletionResponse{}
	mi := &file_proto_shifu_shifu_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionResponse) ProtoMessage() {}

func (x *CompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shifu_shifu_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionResponse.ProtoReflect.Descriptor instead.
func (*CompletionResponse) Descriptor() ([]byte, []int) {
	return file_proto_shifu_shifu_proto_rawDescGZIP(), []int{26}
}

func (x *CompletionResponse) GetCompletions() []string {
	if x != nil {
		return x.Completions
	}
	return nil
}

var File_proto_shifu_shifu_proto protoreflect.FileDescriptor

var file_proto_shifu_shifu_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x68, 0x69, 0x66, 0x75, 0x2f, 0x73, 0x68,
	0x69, 0x66, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x68, 0x69, 0x66, 0x75,
	0x22, 0x1a, 0x0a, 0x18, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x39, 0x0a, 0x19,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x22, 0x2f, 0x0a, 0x13, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6c, 0x6c, 0x53, 0x68, 0x69, 0x66, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x46, 0x0a, 0x14, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6c, 0x6c, 0x53, 0x68, 0x69, 0x66, 0x75, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x20, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x3d, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0x17, 0x0a, 0x15, 0x55, 0x6e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x53, 0x68,
	0x69, 0x66, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x48, 0x0a, 0x16, 0x55, 0x6e,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x53, 0x68, 0x69, 0x66, 0x75, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x14, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3e, 0x0a, 0x13, 0x4c, 0x69,
	0x73, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x27, 0x0a, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x68, 0x69, 0x66, 0x75, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x2d, 0x0a, 0x17, 0x47, 0x65,
	0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x61, 0x0a, 0x18, 0x47, 0x65, 0x74,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0a, 0x65, 0x64, 0x67, 0x65, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x68, 0x69, 0x66,
	0x75, 0x2e, 0x45, 0x64, 0x67, 0x65, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x0a, 0x65, 0x64,
	0x67, 0x65, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x50, 0x49, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x50, 0x49, 0x73, 0x22, 0x7c, 0x0a, 0x06,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x67, 0x65, 0x22, 0xd2, 0x01, 0x0a, 0x0a, 0x45,
	0x64, 0x67, 0x65, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6b, 0x75,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x6b, 0x75, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x22,
	0x75, 0x0a, 0x12, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c,
	0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x2f, 0x0a, 0x13, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72,
	0x64, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x3c, 0x0a, 0x19, 0x52, 0x65, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x68, 0x69, 0x66, 0x75, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x3b,
	0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x68,
	0x69, 0x66, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3d, 0x0a, 0x1a, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x46, 0x0a, 0x1b, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x22, 0x63, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53,
	0x68, 0x69, 0x66, 0x75, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2e, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x53, 0x68, 0x69, 0x66, 0x75, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x22, 0x2a, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x22, 0x44, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x69, 0x73, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x69, 0x73, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x4e, 0x0a, 0x11, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x72, 0x22, 0x36, 0x0a, 0x12, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x32, 0xb2, 0x08, 0x0a, 0x0c, 0x53, 0x68, 0x69, 0x66, 0x75, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x6a, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x25, 0x2e,
	0x73, 0x68, 0x69, 0x66, 0x75, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x73, 0x68, 0x69, 0x66, 0x75, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58,
	0x0a, 0x11, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x73, 0x68, 0x69, 0x66, 0x75, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x68, 0x69, 0x66, 0x75, 0x2e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0c, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6c, 0x6c, 0x53, 0x68, 0x69, 0x66, 0x75, 0x12, 0x1a, 0x2e, 0x73, 0x68, 0x69, 0x66, 0x75,
	0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x53, 0x68, 0x69, 0x66, 0x75, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x68, 0x69, 0x66, 0x75, 0x2e, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6c, 0x6c, 0x53, 0x68, 0x69, 0x66, 0x75, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0e, 0x55, 0x6e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c,
	0x53, 0x68, 0x69, 0x66, 0x75, 0x12, 0x1c, 0x2e, 0x73, 0x68, 0x69, 0x66, 0x75, 0x2e, 0x55, 0x6e,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x53, 0x68, 0x69, 0x66, 0x75, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x68, 0x69, 0x66, 0x75, 0x2e, 0x55, 0x6e, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6c, 0x6c, 0x53, 0x68, 0x69, 0x66, 0x75, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x12, 0x19, 0x2e, 0x73, 0x68, 0x69, 0x66, 0x75, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x73, 0x68, 0x69, 0x66, 0x75, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x12, 0x1e, 0x2e, 0x73, 0x68, 0x69, 0x66, 0x75, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x73, 0x68, 0x69, 0x66, 0x75, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0b, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x50, 0x6f,
	0x72, 0x74, 0x12, 0x19, 0x2e, 0x73, 0x68, 0x69, 0x66, 0x75, 0x2e, 0x46, 0x6f, 0x72, 0x77, 0x61,
	0x72, 0x64, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x73, 0x68, 0x69, 0x66, 0x75, 0x2e, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x50, 0x6f, 0x72,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x46, 0x0a,
	0x12, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x68,
	0x69, 0x66, 0x75, 0x12, 0x20, 0x2e, 0x73, 0x68, 0x69, 0x66, 0x75, 0x2e, 0x52, 0x65, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x68, 0x69, 0x66, 0x75, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x73, 0x68, 0x69, 0x66, 0x75, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x68, 0x69, 0x66, 0x75, 0x12, 0x1f, 0x2e, 0x73, 0x68, 0x69,
	0x66, 0x75, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53,
	0x68, 0x69, 0x66, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x73, 0x68,
	0x69, 0x66, 0x75, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x21, 0x2e, 0x73, 0x68, 0x69, 0x66, 0x75, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x68, 0x69, 0x66, 0x75, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x68, 0x69, 0x66, 0x75, 0x4c, 0x6f, 0x67,
	0x73, 0x12, 0x20, 0x2e, 0x73, 0x68, 0x69, 0x66, 0x75, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x53, 0x68, 0x69, 0x66, 0x75, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x73, 0x68, 0x69, 0x66, 0x75, 0x2e, 0x47, 0x65, 0x74, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x68, 0x69, 0x66, 0x75, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x43, 0x0a, 0x0e, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x15, 0x2e, 0x73,
	0x68, 0x69, 0x66, 0x75, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x73, 0x68, 0x69, 0x66, 0x75, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12,
	0x45, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x18, 0x2e, 0x73, 0x68, 0x69, 0x66, 0x75, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x68,
	0x69, 0x66, 0x75, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x68, 0x6f, 0x6e, 0x69, 0x6e, 0x6c, 0x2f, 0x73, 0x66, 0x74,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x6f, 0x6f, 0x74, 0x2f, 0x77, 0x65, 0x62, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x68, 0x69, 0x66, 0x75, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_shifu_shifu_proto_rawDescOnce sync.Once
	file_proto_shifu_shifu_proto_rawDescData = file_proto_shifu_shifu_proto_rawDesc
)

func file_proto_shifu_shifu_proto_rawDescGZIP() []byte {
	file_proto_shifu_shifu_proto_rawDescOnce.Do(func() {
		file_proto_shifu_shifu_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_shifu_shifu_proto_rawDescData)
	})
	return file_proto_shifu_shifu_proto_rawDescData
}

var file_proto_shifu_shifu_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_proto_shifu_shifu_proto_goTypes = []any{
	(*CheckInstallationRequest)(nil),        // 0: shifu.CheckInstallationRequest
	(*CheckInstallationResponse)(nil),       // 1: shifu.CheckInstallationResponse
	(*InstallShifuRequest)(nil),             // 2: shifu.InstallShifuRequest
	(*InstallShifuResponse)(nil),            // 3: shifu.InstallShifuResponse
	(*GetAllAvailableVersionsRequest)(nil),  // 4: shifu.GetAllAvailableVersionsRequest
	(*GetAllAvailableVersionsResponse)(nil), // 5: shifu.GetAllAvailableVersionsResponse
	(*UninstallShifuRequest)(nil),           // 6: shifu.UninstallShifuRequest
	(*UninstallShifuResponse)(nil),          // 7: shifu.UninstallShifuResponse
	(*ListDevicesRequest)(nil),              // 8: shifu.ListDevicesRequest
	(*ListDevicesResponse)(nil),             // 9: shifu.ListDevicesResponse
	(*GetDeviceDetailsRequest)(nil),         // 10: shifu.GetDeviceDetailsRequest
	(*GetDeviceDetailsResponse)(nil),        // 11: shifu.GetDeviceDetailsResponse
	(*Device)(nil),                          // 12: shifu.Device
	(*Edgedevice)(nil),                      // 13: shifu.Edgedevice
	(*ForwardPortRequest)(nil),              // 14: shifu.ForwardPortRequest
	(*ForwardPortResponse)(nil),             // 15: shifu.ForwardPortResponse
	(*RestartDeviceShifuRequest)(nil),       // 16: shifu.RestartDeviceShifuRequest
	(*Empty)(nil),                           // 17: shifu.Empty
	(*DeleteDeviceShifuRequest)(nil),        // 18: shifu.DeleteDeviceShifuRequest
	(*GetAllContainerNameRequest)(nil),      // 19: shifu.GetAllContainerNameRequest
	(*GetAllContainerNameResponse)(nil),     // 20: shifu.GetAllContainerNameResponse
	(*GetDeviceShifuLogsRequest)(nil),       // 21: shifu.GetDeviceShifuLogsRequest
	(*GetDeviceShifuLogsResponse)(nil),      // 22: shifu.GetDeviceShifuLogsResponse
	(*CommandRequest)(nil),                  // 23: shifu.CommandRequest
	(*CommandResponse)(nil),                 // 24: shifu.CommandResponse
	(*CompletionRequest)(nil),               // 25: shifu.CompletionRequest
	(*CompletionResponse)(nil),              // 26: shifu.CompletionResponse
}
var file_proto_shifu_shifu_proto_depIdxs = []int32{
	12, // 0: shifu.ListDevicesResponse.devices:type_name -> shifu.Device
	13, // 1: shifu.GetDeviceDetailsResponse.edgedevice:type_name -> shifu.Edgedevice
	4,  // 2: shifu.ShifuService.GetAllAvailableVersions:input_type -> shifu.GetAllAvailableVersionsRequest
	0,  // 3: shifu.ShifuService.CheckInstallation:input_type -> shifu.CheckInstallationRequest
	2,  // 4: shifu.ShifuService.InstallShifu:input_type -> shifu.InstallShifuRequest
	6,  // 5: shifu.ShifuService.UninstallShifu:input_type -> shifu.UninstallShifuRequest
	8,  // 6: shifu.ShifuService.ListDevices:input_type -> shifu.ListDevicesRequest
	10, // 7: shifu.ShifuService.GetDeviceDetails:input_type -> shifu.GetDeviceDetailsRequest
	14, // 8: shifu.ShifuService.ForwardPort:input_type -> shifu.ForwardPortRequest
	16, // 9: shifu.ShifuService.RestartDeviceShifu:input_type -> shifu.RestartDeviceShifuRequest
	18, // 10: shifu.ShifuService.DeleteDeviceShifu:input_type -> shifu.DeleteDeviceShifuRequest
	19, // 11: shifu.ShifuService.GetAllContainerName:input_type -> shifu.GetAllContainerNameRequest
	21, // 12: shifu.ShifuService.GetDeviceShifuLogs:input_type -> shifu.GetDeviceShifuLogsRequest
	23, // 13: shifu.ShifuService.ExecuteCommand:input_type -> shifu.CommandRequest
	25, // 14: shifu.ShifuService.GetCompletions:input_type -> shifu.CompletionRequest
	5,  // 15: shifu.ShifuService.GetAllAvailableVersions:output_type -> shifu.GetAllAvailableVersionsResponse
	1,  // 16: shifu.ShifuService.CheckInstallation:output_type -> shifu.CheckInstallationResponse
	3,  // 17: shifu.ShifuService.InstallShifu:output_type -> shifu.InstallShifuResponse
	7,  // 18: shifu.ShifuService.UninstallShifu:output_type -> shifu.UninstallShifuResponse
	9,  // 19: shifu.ShifuService.ListDevices:output_type -> shifu.ListDevicesResponse
	11, // 20: shifu.ShifuService.GetDeviceDetails:output_type -> shifu.GetDeviceDetailsResponse
	15, // 21: shifu.ShifuService.ForwardPort:output_type -> shifu.ForwardPortResponse
	17, // 22: shifu.ShifuService.RestartDeviceShifu:output_type -> shifu.Empty
	17, // 23: shifu.ShifuService.DeleteDeviceShifu:output_type -> shifu.Empty
	20, // 24: shifu.ShifuService.GetAllContainerName:output_type -> shifu.GetAllContainerNameResponse
	22, // 25: shifu.ShifuService.GetDeviceShifuLogs:output_type -> shifu.GetDeviceShifuLogsResponse
	24, // 26: shifu.ShifuService.ExecuteCommand:output_type -> shifu.CommandResponse
	26, // 27: shifu.ShifuService.GetCompletions:output_type -> shifu.CompletionResponse
	15, // [15:28] is the sub-list for method output_type
	2,  // [2:15] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_shifu_shifu_proto_init() }
func file_proto_shifu_shifu_proto_init() {
	if File_proto_shifu_shifu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_shifu_shifu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shifu_shifu_proto_goTypes,
		DependencyIndexes: file_proto_shifu_shifu_proto_depIdxs,
		MessageInfos:      file_proto_shifu_shifu_proto_msgTypes,
	}.Build()
	File_proto_shifu_shifu_proto = out.File
	file_proto_shifu_shifu_proto_rawDesc = nil
	file_proto_shifu_shifu_proto_goTypes = nil
	file_proto_shifu_shifu_proto_depIdxs = nil
}
